#Build configuration
os: Visual Studio 2017
before_build:
  - dotnet --info
  - dotnet restore  
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
# build Configuration, i.e. Debug, Release, etc.
configuration: Debug